sudo: required

services:
  - docker

install:
  - docker build --tag bodsch/docker-dnsdock .
  - docker run --detach --name dnsdock bodsch/docker-dnsdock --nameserver="141.1.1.1:53"

script:
  - docker ps | grep -q dnsdock

